insert into SONG (id, title, author, album, category, votes) values (1, 'Rain Over Santiago ', 'Timoteo Kasting', 'JPY', 'SWING', '62555');
insert into SONG (id, title, author, album, category, votes) values (2, 'Going the Distance', 'Parke Bransom', 'IDR', 'SOUL', '835');
insert into SONG (id, title, author, album, category, votes) values (3, 'New York Confidential', 'Gaelan Hardin', 'SEK', 'POP', '42');
insert into SONG (id, title, author, album, category, votes) values (4, 'Gorky Park', 'Melloney Buttrum', 'EUR', 'POP', '48');
insert into SONG (id, title, author, album, category, votes) values (5, 'In America', 'Joellyn Sancroft', 'YER', 'ELECTRO', '371');
insert into SONG (id, title, author, album, category, votes) values (6, 'Stranger The', 'Kevina Bryce', 'UGX', 'ELECTRO', '44');
insert into SONG (id, title, author, album, category, votes) values (7, 'Doctor Zhivago', 'Arie Gillyett', 'XOF', 'ROCK', '7');
insert into SONG (id, title, author, album, category, votes) values (8, 'Phone Booth', 'Walker Tomney', 'EUR', 'ROCK', '37275');
insert into SONG (id, title, author, album, category, votes) values (9, 'Ouija', 'Derk Jerrim', 'USD', 'HEAVY_METAL', '347');
insert into SONG (id, title, author, album, category, votes) values (10, 'Chocolate Soldier The', 'Vania Dyka', 'CNY', 'JAZZ', '8489');
insert into SONG (id, title, author, album, category, votes) values (11, 'Other Dream Team The', 'Benita Smeeton', 'EUR', 'JAZZ', '13');
insert into SONG (id, title, author, album, category, votes) values (12, 'Last Polka The', 'Colette Judson', 'LBP', 'ELECTRO', '8');
insert into SONG (id, title, author, album, category, votes) values (13, 'Original Kings of Comedy The', 'Isidore Sparwell', 'PHP', 'SWING', '3133');
insert into SONG (id, title, author, album, category, votes) values (14, 'Underworld Rise of the Lycans', 'Harland Fancy', 'LKR', 'JAZZ', '660');
insert into SONG (id, title, author, album, category, votes) values (15, 'Lisztomania', 'Glenn Birchner', 'RUB', 'POP', '3088');
insert into SONG (id, title, author, album, category, votes) values (16, 'How to Eat Your Watermelon in White Company', 'Kahaleel Ivanshintsev', 'EUR', 'POP', '1772');
insert into SONG (id, title, author, album, category, votes) values (17, 'Marvellous', 'Johann Collerd', 'THB', 'ROCK', '28');
insert into SONG (id, title, author, album, category, votes) values (18, 'Terror The', 'Adan Smouten', 'CNY', 'ROCK', '4');
insert into SONG (id, title, author, album, category, votes) values (19, 'RoboCop 2', 'Andriana Imm', 'IDR', 'SWING', '964');
insert into SONG (id, title, author, album, category, votes) values (20, 'Fifty Pills', 'Helyn Rosenwald', 'MAD', 'SWING', '4');
insert into SONG (id, title, author, album, category, votes) values (21, 'WednesdayA', 'Averyl Anscombe', 'IDR', 'POP', '849');
insert into SONG (id, title, author, album, category, votes) values (22, 'Picture of Dorian Gray The', 'Arlie Dyerson', 'SEK', 'ROCK', '54');
insert into SONG (id, title, author, album, category, votes) values (23, 'WhistleblowerThe', 'Naoma Duggan', 'PHP', 'ROCK', '4806');
insert into SONG (id, title, author, album, category, votes) values (24, 'Los Flamencos', 'Dougy Culshaw', 'CUP', 'SWING', '25');
insert into SONG (id, title, author, album, category, votes) values (25, 'AI Artificial Intelligence', 'Base Teape', 'IDR', 'ROCK', '565');
insert into SONG (id, title, author, album, category, votes) values (26, 'Manufactured Landscapes', 'Sib Sealeaf', 'IDR', 'POP', '35284');
insert into SONG (id, title, author, album, category, votes) values (27, 'Keith Lemon The Film', 'Wit Harteley', 'CNY', 'HEAVY_METAL', '54483');
insert into SONG (id, title, author, album, category, votes) values (28, 'Cthulh4324234b u', 'Calley Scotti', 'CNY', 'POP', '601');
insert into SONG (id, title, author, album, category, votes) values (29, 'Mall', 'Pearla Catchpole', 'KYD', 'JAZZ', '598');
insert into SONG (id, title, author, album, category, votes) values (30, 'Dragonheart 3 The Sorcerers Curse', 'Tabina Vinick', 'IDR', 'ROCK', '8');
insert into SONG (id, title, author, album, category, votes) values (31, 'Good Man in Africa A', 'Darcee McCaffrey', 'TZS', 'ROCK', '6162');
insert into SONG (id, title, author, album, category, votes) values (32, 'Cadence', 'Yalonda Edwin', 'CNY', 'POP', '6');
insert into SONG (id, title, author, album, category, votes) values (33, 'Happy Birthday to a Beautiful Woman', 'Shela Beisley', 'IDR', 'ELECTRO', '3');
insert into SONG (id, title, author, album, category, votes) values (34, 'Kinsey', 'Cointon Bloxam', 'EUR', 'SWING', '4');
insert into SONG (id, title, author, album, category, votes) values (35, 'Marvellous', 'Giusto Kirkbride', 'RUB', 'ROCK', '379');
insert into SONG (id, title, author, album, category, votes) values (36, 'Itinerary of a Spoiled Child', 'Coralyn Rosenvasser', 'EUR', 'ELECTRO', '969');
insert into SONG (id, title, author, album, category, votes) values (37, 'Algiers', 'Teresina Henrionot', 'CNY', 'SWING', '04');
insert into SONG (id, title, author, album, category, votes) values (38, 'Streets of Blood', 'Madelin Cresser', 'COP', 'SWING', '4026');
insert into SONG (id, title, author, album, category, votes) values (39, 'Cry of the City', 'Yankee Vakhrushev', 'RUB', 'POP', '295');
insert into SONG (id, title, author, album, category, votes) values (40, 'First 20 Million Is Always the Hardest The', 'Elbert Filintsev', 'MKD', 'ELECTRO', '41');
insert into SONG (id, title, author, album, category, votes) values (41, 'Rat King', 'Celinka OCahey', 'CAD', 'POP', '8208');
insert into SONG (id, title, author, album, category, votes) values (42, 'KinoEye Kinoglaz', 'Boony Stonary', 'IRR', 'ELECTRO', '70');
insert into SONG (id, title, author, album, category, votes) values (43, 'Dabangg 2', 'Evie Stockwell', 'TZS', 'SWING', '47661');
insert into SONG (id, title, author, album, category, votes) values (44, 'Roadracers', 'Nelli Jirick', 'JMD', 'SOUL', '41');
insert into SONG (id, title, author, album, category, votes) values (45, 'Walk in  323 he Sun, A', 'Penn Vinick', 'IDR', 'JAZZ', '80548');
insert into SONG (id, title, author, album, category, votes) values (46, 'Ogre The Unhold Der', 'Ardelia Wight', 'JPY', 'ROCK', '14');
insert into SONG (id, title, author, album, category, votes) values (47, 'Ace of HeartsThe', 'Wheeler Copsey', 'USD', 'ROCK', '79338');
insert into SONG (id, title, author, album, category, votes) values (48, 'Japanese Summer Double Suicide', 'Ethe Bilney', 'COP', 'HEAVY_METAL', '7');
insert into SONG (id, title, author, album, category, votes) values (49, 'Paraso Travel', 'Berni Ranson', 'EUR', 'ROCK', '10');
insert into SONG (id, title, author, album, category, votes) values (50, 'World Without End', 'Rodd Mosten', 'JPY', 'POP', '49');